eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    service-url:
      defaultZone: http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb
      host: atlas-cluster.mqdj7js.mongodb.net
      port: 27017
      database: orderdb
      repositories:
        enabled: true
